//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ses1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myEntities : DbContext
    {
        public myEntities()
            : base("name=myEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KOMNATA_OBSH> KOMNATA_OBSH { get; set; }
        public virtual DbSet<KORPUS_OBSH> KORPUS_OBSH { get; set; }
        public virtual DbSet<MESTO_OBSH> MESTO_OBSH { get; set; }
        public virtual DbSet<OBSH> OBSH { get; set; }
        public virtual DbSet<STATUS_OBSH> STATUS_OBSH { get; set; }
        public virtual DbSet<Zayvki> Zayvki { get; set; }
    }
}
