//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ses1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBSH
    {
        public int ID { get; set; }
        public int ID_KORPUS { get; set; }
        public int ID_KOMNATA { get; set; }
        public Nullable<int> ID_MESTO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
    
        public virtual STATUS_OBSH STATUS_OBSH { get; set; }
    }
}
