//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ses1
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_OBSH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATUS_OBSH()
        {
            this.OBSH = new HashSet<OBSH>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> STATUS_SOTRUDNIK { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public Nullable<System.DateTime> DZ { get; set; }
        public Nullable<System.DateTime> DV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBSH> OBSH { get; set; }
    }
}
