//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ses1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayvki
    {
        public int id_zayvki { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Sait { get; set; }
    }
}
